### PR TITLE
Add intelrapl.pm to monitor the power consumption of intel-rapl capable devices.

### PR DESCRIPTION
**Pull request by bachandi**
This plot lets you monitor the power draw of intel-rapl capable devices by reading the energy counters and calculating the power draw.

Example 1:
Bildschirmfoto 2022-01-30 um 14 54 18

Example 2:
Bildschirmfoto 2022-01-29 um 02 14 14

### CODE REVIEW

**Comment by mikaku** [comment]
Is this an only-one graph module? which would mean that all the values in the graph are related.

if so, I think these lines look like a hack:

```
$height *= 1.2;
$width += 300;
```
Perhaps we should include a new graph size in `graph_size` to cover the case of modules with only one graph while keeping a correct layout and adjustment with the rest of modules.

**Comment by mikaku** [comment]
Also, why you have an orange title in your graphs?
Do you have your own theme or it's a bug?

**Comment by bachandi** [comment]
> Is this an only-one graph module?

Yes. 

> Perhaps we should include a new graph size in `graph_size` to cover the case of modules with only one graph while keeping a correct layout and adjustment with the rest of modules.

This is the way. Maybe `huge` or `large` as a new `graph_size`?

BTW: Most of the comments for this PR will also apply PR #389.

**Comment by bachandi** [comment]
> Also, why you have an orange title in your graphs?
> Do you have your own theme or it's a bug?

Yes, I have a custom css. I forgot to change it back before taking the screenshot.

**Comment by mikaku** [comment]
> BTW: Most of the comments for this PR will also apply PR https://github.com/mikaku/Monitorix/pull/389. I will update PR https://github.com/mikaku/Monitorix/pull/389 if this one is ready.

Yes.

**Comment by mikaku** [comment]
Thanks.

**Comment by mikaku** [comment]
intelrapl

I'm using the default configuration in `monitorix.conf`.
Looks like something needs to be fixed.

**Comment by mikaku** [comment]
Also, why the image names `intelrapl00.1day.png` have 2 numerical digits?
I mean, what is the purpose of the second digit?

**Comment by bachandi** [comment]
> Also, why the image names `intelrapl00.1day.png` have 2 numerical digits?
> I mean, what is the purpose of the second digit?

Yes, thats the reason for your errors. Will fix it.

**Comment by bachandi** [comment]
It should both be fixed in PR #396

**Pull request merged**
