### PR TITLE
Fix image filename problem in intelrapl

### LINKED ISSUE #395: Image filename problem in intelrapl
intelrapl

I'm using the default configuration in `monitorix.conf`.
Looks like something needs to be fixed.

```
Use of uninitialized value in concatenation (.) or string at /home/mikaku/github/monitorix/lib/intelrapl.pm line 738.
Use of uninitialized value in concatenation (.) or string at /home/mikaku/github/monitorix/lib/intelrapl.pm line 744.
Use of uninitialized value in concatenation (.) or string at /home/mikaku/github/monitorix/lib/intelrapl.pm line 760.
Use of uninitialized value in concatenation (.) or string at /home/mikaku/github/monitorix/lib/intelrapl.pm line 766.
Use of uninitialized value in multiplication (*) at /home/mikaku/github/monitorix/lib/intelrapl.pm line 775.
Use of uninitialized value in multiplication (*) at /home/mikaku/github/monitorix/lib/intelrapl.pm line 776.
Use of uninitialized value $params{"IMGz"} in sprintf at /home/mikaku/github/monitorix/lib/Monitorix.pm line 101.
Use of uninitialized value $params{"IMG"} in sprintf at /home/mikaku/github/monitorix/lib/Monitorix.pm line 78.
```

_Originally posted by @mikaku in https://github.com/mikaku/Monitorix/pull/390#issuecomment-1031210467_

### PR DESCRIPTION
**Pull request by bachandi**
Fixes #395

### CODE REVIEW

**Comment by mikaku** [comment]
I see that `my $n_plot = 0;` fixes it, but I'm still unable to understand why we need the second digit in the image name.

**Comment by bachandi** [comment]
> I see that `my $n_plot = 0;` fixes it, but I'm still unable to understand why we need the second digit in the image name.

It is not needed at the moment. It is just representing the first plot for this module. Seemed consistent to me to have all image name contain the index even if there is only one.

**Comment by mikaku** [comment]
> It is just representing the first plot for this module

How is counted the first plot?
In the default configuration there are defined 2 graphs:

```
<list>
        0 = core, uncore, package, dram
        1 = dram
</list>
```

I expected to have image names like `intelrapl0.1day.png` and `intelrapl1.1day.png`, since there shouldn't be any relationship between both images.

The fact that you are reserving a second digit means that the images are somehow related each other, but I don't see how.
Also, the jump from `00` to `10` might confuse to people that parses the HTML from a script to get the images individually.

**Comment by bachandi** [comment]
> The fact that you are reserving a second digit means that the images are somehow related each other, but I don't see how. Also, the jump from `00` to `10` might confuse to people that parses the HTML from a script to get the images individually.

To not have this confusion I changed the naming scheme to `intelrapl0_0.1day.png`, `intelrapl1_0.1day.png`, `intelrapl2_0.1day.png` and so on. This way there is no issue with parsing these names and the `_0` just indicates it is the first plot.

Actually having both indices concatenated directly complicates parsing for images from all other modules that use this as one always has to know how many plots there are (or how many digits it takes) and in general is actually not safe when having large numbers for both indices:
The indices `n1 = 1` and `m1 = 11` and `n2 = 11` and `m2 = 1` both result in `111` when just concatenated so there is no way to distinguish them anymore.
Having a separator between the indices would simplify parsing as one can always check for the underscore to get the separate indices.

**Comment by mikaku** [comment]
> This way there is no issue with parsing these names and the _0 just indicates it is the first plot.

Still I don't understand the meaning of that `_0`. What is the purpose of that extra index? it could be more than zero? if so, in which case?

Monitorix uses the double index notation (without separator) for these graphs that belong to an unlimited number of groups, which as far as I understand, this is not the case in this module (correct me if I'm wrong).

This kind of notation is the same in all modules. We shouldn't change this criteria now as there might be scripts based on it, and would include some confusion and incoherence.

**Comment by mikaku** [comment]
OK, so I can assume that this module keeps the logic as:
- `00` = first graph of the first group.
- `01` = second graph of the first group.
- `10` = first graph of the second group.
- etc.

Right?

**Comment by bachandi** [comment]
> OK, so I can assume that this module keeps the logic as:
> 
> * `00` = first graph of the first group.
> * `01` = second graph of the first group.
> * `10` = first graph of the second group.
> * etc.
> 
> Right?

Yes

**Comment by mikaku** [comment]
Thanks.

**Comment by mikaku** [comment]
One more thing. The problem I see in this graph is that it doesn't appear to have two groups because the two graphs are inside the same `<table>`. I think that's the reason why it keeps confusing me.

If you look into the rest of modules, different groups are normally setup in separated `<table>`.

**Comment by bachandi** [comment]
> One more thing. The problem I see in this graph is that it doesn't appear to have two groups because the two graphs are inside the same `<table>`. I think that's the reason why it keeps confusing me.
> 
> If you look into the rest of modules, different groups are normally setup in separated `<table>`.
> 
> I think you are giving a new sense to the representation:
> 
> ```
> <list>
>         0 = core, uncore, package, dram
>         1 = dram
> </list>
> ```
> 
> Does this mean that there are 2 groups with one graph on each group, or one group with two graphs?

Two groups, with one plot for each group. The table frame is for the complete module and not per group. As there is only one plot for each group it looked a bit silly otherwise but I can change this if you don't like it this way.

**Comment by mikaku** [comment]
But, if they are separated groups, why there is the same graph name `dram` but appears different on each group?

I mean, `dram` in the first group looks like embedded in the graph, while in the second group appears individually. What makes it change?

**Comment by bachandi** [comment]
> But, if they are separated groups, why there is the same graph name `dram` but appears different on each group?

It is the same graph in two groups. I just wanted to give an example how to use the groups. Users might want to have DRAM in a separate graph and remove it from the first group or in the same group remove the second group. And to show how to add a second group in case someone has to CPU sockets and wants them in separate groups.

> I mean, `dram` in the first group looks like embedded in the graph, while in the second group appears individually. What makes it change?

That is just an issue of DRAM being alone in the second group(graph). If you add additional sensors it will soon look like the first graph.

**Comment by mikaku** [comment]
By the way, the zoomed-in graph looks smaller than the default graph, this is an effect of having a so `large` graph.

**Comment by bachandi** [comment]
> So, the values can simply be represented stacked or not in the graph depending if they are grouped in the same key value (0, 1, etc.)? Well, this is new in Monitorix and I'm not sure that the current manpage reflects this behavior.
> 
> And if they can be all staked in a unique graph, I don't see yet the concept of a group in this module (sorry to insist of that).

No, nothing is stacked in this graph but if you like you can define a sum graph via <sum> for each group. 

One thing is missing in the documentation. The `core` key name is special as it will be drawn with a filled area. I would need to mention this behaviour in the documentation. To have a normal line a user would just need to use a different key name.

**Comment by bachandi** [comment]
> By the way, the zoomed-in graph looks smaller than the default graph, this is an effect of having a so `large` graph.

The browser probably decreases the popup size if it is too large?

**Comment by mikaku** [comment]
> The browser probably decreases the popup size if it is too large?

No, this looks like an effect of the `--full-size-mode` parameter introduced in the previous version.

**Pull request merged**
