### PR TITLE
Add nvidiagpu.pm with more sensor readings.

### LINKED ISSUE #333: nvidia-smi has also fan information. It would be nice to have that also as graph in the nvidia info.
https://github.com/mikaku/Monitorix/blob/9b28b53374fe39038b55d34d6d6c200348de42d3/lib/nvidia.pm#L199

### PR DESCRIPTION
**Pull request by bachandi**
This is a plot collection using `nvidia-smi` with more information than the default nvidia.pm.
It has monitoring (if supported by the device/driver) for:
- Fan percentage
- Core temperature
- Memory temperature
- Memory usage
- Power consumption and set limit
- Core utilization
- Memory utilization
- Core clock
- Memory clock
- Performance state

I didn't replace the old nvidia.pm because maybe someone might still prefer the smaller plot collection?

Bildschirmfoto 2021-12-08 um 08 44 53

This would also fix #333.

### CODE REVIEW

**Comment by bachandi** [comment]
Fixed the merge conflicts.

**Comment by mikaku** [comment]
Why are you forcing to delimit the items with an extra space after the comma? (line 180)

**Comment by bachandi** [comment]
> 1. Why are you forcing to delimit the items with an extra space after the comma? (line 180, 478, ...).

This is just the same delimit logic as in disk.pm. Thought it should be consistent but no need for forcing the space. We could remove this requirement if you like.

> 2. Why are you not using the default function `celsius_to()` in `lib/Monitorix.pm` to convert to Fahrenheit?

The temperature data is stored in degrees Celsius. The conversion is only needed if displaying in Fahrenheit is requested. So we can just use the CDEF to convert them to Fahrenheit. `celsius_to()` converts the value directly and can't be used as CDEF formula.

> 3. In `Makefile` you put `nvidiagpu.pm` after `nvidia.pm` while in the rest of options you put it before.

In the Makefile it was said to be in alphabetical order so I put it afterwards. No strong feeling about where to place it in the rest.

**Comment by bachandi** [comment]
Thanks.

**Comment by mikaku** [comment]
Thanks.

**Pull request merged**
