### PR TITLE
NUT updates

### LINKED ISSUE #401: [feature] limit range of values
Is it possible to cutoff graff with unused values to be more detailed

adding examples
image

cutted one
image

second one apc ups have more values with is used to cut from 0-140v
but NUT ups do not report such values

Is it possible option to be added somewhere in configuration limits, so user manually to set minimum maximum area values?

### PR DESCRIPTION
**Pull request by bachandi**
- Add `use_nan_for_missing_data` option (This would also fix #401).
- Add `gap_on_all_nan` option to show gaps only if all data points are nan instead of requiring only one to be nan for a gap.
- Add `ignore_error_output` option. When enabled, suppresses error output from upsc.
- ~~Use the css style instead of `title_fg_color` and `title_bg_color`.~~

### CODE REVIEW

**Comment by mikaku** [comment]
I have some questions on this:

1. Does the new option `ignore_error_output` is really needed? if so, in which cases?
2. Why are you changing the CSS in this graph?
3. Why this graph fixes the issue #401?

Also, if you plan to use a variable to include the whole command line, you should also change the line [190](https://github.com/mikaku/Monitorix/blob/e3efbfe607ad550bb812c162655f0232dc9d8ca2/lib/nut.pm#L190).

**Comment by mikaku** [comment]
> I thought the CSS is handling the style of the page. Up to now it uses the (old?) style config from the config file $colors->{title_fg_color}. Is this the desired location to configure the style? This makes it difficult to have custom CSS styles.

You're right, I forgot to apply the CSS changes to these modules that need to show a value in the bottom of the graph.

I think though, that it would be better for the commit history if all these CSS changes in the pending modules are pushed in only one commit separately.

**Comment by bachandi** [comment]
> I think though, that it would be better for the commit history if all these CSS changes in the pending modules are pushed in only one commit separately.

Right, I rebased this branch to remove the css commit. Will create a new branch and PR for this css style change.

**Comment by mikaku** [comment]
Thanks.

**Comment by Saentist** [comment]
@bachandi 
> * Add `use_nan_for_missing_data` option (This would also fix [[feature] limit range of values #401](https://github.com/mikaku/Monitorix/issues/401)).

This absolutely not solve problem, when UPS not send data for minimum maximum transfer 
and cut unneeded 0-160V area

You are mistaken from word "missing" actually data never exist, it's not reported by NUT, as on APC.
Guess you interpret it as "existing" and "missing from time to time".
for this is Feature request #401 
with make voltage line flatten and not good visible when used range 0-250 in place of 180-260
aka cut horizontal area not for adding gap in vertical

@mikaku reopen #401

**Comment by mikaku** [comment]
@Saentist, can you, please, paste here the whole section `<nut>` from your configuration?

**Comment by Saentist** [comment]
> @Saentist, can you, please, paste here the whole section `<nut>` from your configuration?

```
# NUT graph
# -----------------------------------------------------------------------------
<nut>
       list = ups@localhost
       rigid = 0, 2, 0, 0, 0, 0
       limit = 100:0, 100, 100:0, 100:0, 100:0, 100:0
</nut>
```

**Comment by bachandi** [comment]
> ```
> # NUT graph
> # -----------------------------------------------------------------------------
> <nut>
>        list = ups@localhost
>        rigid = 0, 2, 0, 0, 0, 0
>        limit = 100:0, 100, 100:0, 100:0, 100:0, 100:0
> </nut>
> ```

You need to add `use_nan_for_missing_data = y` and maybe `alt_scaling_for_voltage = y`.

Missing data means, that the values are not reported at all. The missing values will be set to `nan` (instead of `0`) and ignored when the graph scales its axis. But the `0` values you have in your database up to now won't go away so the effect of this change will be visible in the hourly plots first.

The alternative scaling option can be set to improve the axis scaling but without the missing data option it can't work on graphs with `0`s.

**Comment by Saentist** [comment]
@bachandi 
This is Feature request are for.

**Comment by bachandi** [comment]
> This is Feature request are for.

Just add `use_nan_for_missing_data = y` to your `<nut>` config and your missing values for `input.transfer.high` and `input.transfer.low` will be set to `nan` (instead of `0`). This will fix your scaling problem.

**Comment by Saentist** [comment]
And result is ...
image

**Comment by bachandi** [comment]
> And result is ...
> image

As I said. Your old `0`  values are still in the database. It will first be visible in the scaling after an hour in the hourly graph and after a day in the daily graph and so on. But small red line on the bottom of your graph will stop to continue and the values in the legend for transfer low and high will be nan sooner. But for the scaling to take effect it will take time till your old `0` values go out of scope.

**Comment by Saentist** [comment]
image
no comment

**Comment by bachandi** [comment]
> image
> no comment

This is because you have `show_graphs` enabled. As the documentation says you need to set `gap_on_all_nan = y` in this case.

Please add `gap_on_all_nan = y` also to your `<nut>` config.

**Comment by Saentist** [comment]
will try 
by the way some of graphs work
image

**Comment by bachandi** [comment]
> will try
> by the way some of graphs work

Yes. That is because in those graphs for _Battery voltage_ and _Line Frequency_ there is no missing data. So these don't show any gaps. Your `Time left` graph will stay white as your UPS does not provide that information.

**Comment by Saentist** [comment]
> alt_scaling_for_voltage = y

image

Still question is:
how to set "manual/fake" values in this case for ```input.transfer.low```
and cut/remove unused area fom 0 to 170

**Comment by bachandi** [comment]
> image
> 
> Still question is: how to set "manual/fake" values in this case for `input.transfer.low` and cut/remove unused area fom 0 to 170

There is still a small remnant of the old `0` values in the lower left corner. Please wait about ~5 minutes more and check the plot again. The area you mentioned should be gone by then.

**Comment by Saentist** [comment]
They are switched to -nan

image

**Comment by bachandi** [comment]
> They are switched to -nan

Great, finally you also need to remove the lower axis limit in you `nut` config. To do so please replace the line:
`limit = 100:0, 100, 100:0, 100:0, 100:0, 100:0`
by
`limit = 100, 100:0, 100, 100, 100, 100`

**Comment by Saentist** [comment]
OK some success
image
alt_scaling_for_voltage = n
image
alt_scaling_for_voltage = y


Never ever use CEZ as electrical operator, by normative voltage must be 230V

**Comment by bachandi** [comment]
The `alt_scaling_for_voltage` option is really dependent on your data so just check if enabled or disabled suits you better.

I hope the issue is fixed?

**Comment by Saentist** [comment]
Alt scalling is good in zoomed image, bad in regular view, in my case

**Comment by bachandi** [comment]
> is it possible to see values in zoomed image

No, the current and average values are only shown in the normal plots not the zoomed ones.

**Comment by Saentist** [comment]
> > is it possible to see values in zoomed image
> 
> No, the current and average values are only shown in the normal plots not the zoomed ones.

Mistyped, i mean to see more detailed values in vertical.
Without alt scaling there are 6 values, but with, they are only two.  
image

**Comment by bachandi** [comment]
> Mistyped, i mean to see more detailed values in vertical. Without alt scaling there are 6 values, but with, they are only two.

This is handled by RRDtool. Monitorix does not have direct influence on the automatic scaling besides switching to the alternative scaling. 

You can set fixed upper and lower bounds via the `rigid` and `limit` options but then you loose the automatic y-axis scaling.

But this is out of scope for this PR.

**Pull request merged**
