### PR TITLE
GitHub Actions for "Syntax Checking" & "Basic Testing"

### PR DESCRIPTION
**Pull request by hummeltech**
**This adds basic sanity checks for `Monitorix` using several distributions, the steps are as follows:**
  * Package dependencies are installed
  * Perl module dependencies are installed
  * Code is syntax checked
  * Monitorix is `"installed"`
  * Monitorix is `"started"` & several URLs are fetched
    * For both `PNG` and `SVG` image formats
  * Generated `www` & `log` artifacts are uploaded to GitHub
    * For potential manual review of e.g. images

See [here](https://github.com/hummeltech/Monitorix/actions/runs/1617562728) for an example of a test run.

### CODE REVIEW

**Comment by mikaku** [comment]
CentOS 8 will be EOL in a week (31-dec-2021), so better use Rocky 8 instead.

**Comment by hummeltech** [comment]
Good point, I almost forgot, [here's a new workflow run](https://github.com/hummeltech/Monitorix/actions/runs/1615175686) using AlmaLinux 8 rather than CentOS 8.

**Comment by mikaku** [comment]
Beware using Alma Linux 8, they sometimes introduce their own patches and the system might be slightly different than a genuine RHEL. Instead, Rocky 8 follows the same path than CentOS 8. Even better.

**Comment by hummeltech** [comment]
Sounds good, thanks, [here](https://github.com/hummeltech/Monitorix/actions/runs/1615990799) is a new workflow run!

**Comment by hummeltech** [comment]
As I see you merged in my old pull request (that's awesome), I switched to `Rocky Linux 8` and rebased this branch in order to also check that new code, [here](https://github.com/hummeltech/Monitorix/actions/runs/1616080080) is a new workflow run.

**Comment by mikaku** [comment]
Excellent, thank you very much.

**Comment by hummeltech** [comment]
Sure thing, I was happy to help! Let me know if you ever need assistance with it!

**Comment by mikaku** [comment]
> Let me know if you ever need assistance with it!

I'll do. Thanks again.

**Pull request merged**
