### PR TITLE
Correct ProFTPD log file

### PR DESCRIPTION
**Pull request by borzaka**
image

### CODE REVIEW

**Comment by mikaku** [comment]
Hi,

Since this is Debian specific, this should modify the extra configuration file called `debian.conf`, which it resides inside the `docs/` directory.

Also, the `/var/log/proftpd/access.log` path is subjected to the `ExtendedLog` option, as stated in `monitorix.conf.5`:

```
For best results with the ProFTPD server I recommend to add the following line in its configuration file:

       ExtendedLog /var/log/proftpd/access.log AUTH,DIRS,READ,WRITE
```

So, I recommend to not change this option if you are going to follow what the Monitorix documentation recommends.

**Comment by borzaka** [comment]
I would expect it to work out-of-the box without any extra modification. And if anybody reads the manual (no offense), they can update the Monitorix and the ProFTPD configs to use as the recommended way for the best results.
But for now it's just not working right away.

I see two possible options:
1. add a note to the `monitorix.conf` `ftp_log` line that user needs to read the manual and act accordingly to make that work
2. edit `debian.conf` and add ProFTPD default logfile there to work at least on Debian systems out-of-the-box somewhat

But if I add `ftp_log = /var/log/proftpd/proftpd.log` to the `debian.conf`, than it will override the same setting in the `monitorix.conf`, right? So if I later add `ExtendedLog` to my ProFTPD configs, I have to re edit my `debian.conf` as well.

My goal would be to make this working right away, and user may extend it later.

**Comment by mikaku** [comment]
Can you, please, include the patch with the note in the `monitorix.conf` `ftp_log` line?
Just to make me an idea of how this would be.

**Comment by mikaku** [comment]
Resolved with pull request #253

**Pull request closed without merging**
