### PR TITLE
Added Bootstrap theme

### PR DESCRIPTION
**Pull request by niutech**
Based on Bootstrap 3.

Notice: Sometimes images could be not properly floated, it could be fixed by changing the order of rendered images in HTML (first the big one on the left, then two small stacked on the right, then another big one on the left).

### CODE REVIEW

**Comment by mikaku** [comment]
I see several issues:

-  there is a missing closing `</style>` in the `index.html` which results in a problem for the browser when interpreting that file.
- some graph layouts are broken and this is completely unacceptable.
- although I find the look pretty ugly I can understand that someone might like it, the problem is that there is not way to select which theme you want ('classic' or 'that bootstrap').
- consider first to update your files in order to avoid merging with the branch 'master'.

Thanks.

**Comment by niutech** [comment]
- The missing </style> has been fixed in commit f0c8d51f, although it should not make any problem (all browsers silently ignore that error)
- As it was stated in the description, images could be wrongly floated only if two wide images are outputted one by one. It could be easily fixed by changing the order in which `s are put in HTML (one wide image, then two small stacked images). In most panels the images look fine:

pic1

Another way to fix the image floating issue is to use CSS Flexbox, which is still not supported in every web browser.

**Comment by mindeunix** [comment]
Maybe someone can explain why it is necessary to load 100K+ stylesheet to accomplish such as simple task? I also have few machines that works in intranet/local network so there is no simple way to reach this file.

**Comment by IzzySoft** [comment]
Apart from the size of the stylesheet (as pointed out by @mindeunix in the previous comment), and though the fact that (arguing from the screenshot) I find it looks refreshing (iow, I somehow like the look), I'm opposing this merge. @mikaku will remember we've had the argument before concerning styling – and also mentioned the main reason for my opposition: the fact "that there is not way to select which theme you want". Solely for that reason (in combination with the huge overhead by all those stylesheets introduced) currently this is a no-go.

@niutech no harsh feelings. But consider *Monitorix* also runs on low-spec devices (e.g. RasPi/BananaPi), or on devices with no contact to the "outer world" so external stylesheets cannot be loaded. Moreover, this is a "tech tool" for monitoring, where "fancy stuff" must stay back behind "hard facts" :)

@mikaku As I wrote, we've had this topic multiple times in the past. And here, I strongly agree with you: it's hard to find a "one fits all". So bringing up my argument from "back then": to allow such stylings, we need first to make the page "template driven". I know you lack the time for that, and I lack experience/knowledge in Perl – so we need to find another volunteer :)

**Comment by niutech** [comment]
If you don't want to make Monitorix look more modern, it's fine. I'll
keep that theme for myself. Ideally, there should be a theming engine
with pluggable themes to separate concerns.

**Comment by IzzySoft** [comment]
> If you don't want to make Monitorix look more modern, it's fine.

That's not the point. Point is "the price to pay" (i.e. the dependencies you bring in) is too heavy.

> Ideally, there should be a theming engine with pluggable themes to separate concerns.

That's what I wrote above – call it theme or call it template :)

**Comment by mikaku** [comment]
> If you don't want to make Monitorix look more modern, it's fine.

As @IzzySoft already stated, that's not the point.

Please don't get us wrong. We are all mind-opened to include new features to Monitorix and, indeed, having the ability to select a modern look would be very interesting. But the reality is that not much people helped on this, and the only ones that came with nice ideas seem that they are all vanished with the time. Please, take a look into issue #53.

I'm not expert enough in CSS, HTML or JavaScript as you seem are, but I think we can work together in order to change the old and rigid HTML code produced by Monitorix into something more dynamic and *themeable*. Of course, that include work on your part and also on my part. Both need to work hard to offer a serious, consistent and working final product.

I invite you to join to #monitorix IRC channel at freenode to talk directly with us and share your ideas of how we can accomplish this.

Thanks.

**Comment by gsouf** [comment]
You can have a more modern style without using bootstrap, a very few css might be enough to modernize the  UI and keep compatiblity with all systems.

**Comment by IzzySoft** [comment]
Sure we can, and that's the way most of us would prefer. Just someone would need to go over the code and replace the "hardcoded formatting" by CSS classes, moving the current style (as-is) to a `default.css`. With that done (and approved by @mikaku ), just the CSS had to be modified. Basically at least.

Of course much more *could* be done theoretically – but that would mean more than just "string replacements" in the code, namely using a template engine. While I'm pretty sure @mikaku wouldn't oppose the first approach (moving hardcoded formatting to CSS), rewriting for a template engine is a quite different thing. Not sure whether Jordi even had the time to review that properly. But that's not for me to say :)

**Comment by gonace** [comment]
So I've been looking at this discussion and work, I'm not sure this have been done as I would like, there should be a template system for Monitorix and removal of all html rendering and leeting the template system handle it. 

Just swapping and old html to a new (that soon will be old) is just a waste of time, right? Keep it simple, move it to a template system, and keeping the templates up to date will be less of a hassle?

**Comment by mikaku** [comment]
@gonace, as I stated several times, I can change the current HTML code by the code you want, expecting that your template will render it in, as a minimum, the same *classic* view, and optionally as a new *modern* view.

As long as you can do that we can start talking on this.

Let me repeat. The *classic* view must be kept exactly as it is. I think that this won't be a problem for your (new/modern) rendering engine.

**Pull request closed without merging**
