### PR TITLE
fix Makefile for debian.conf

### PR DESCRIPTION
**Pull request by graysky2**

### CODE REVIEW

**Comment by Tarjaizaid** [comment]
Hey,

If user add specific option for http/mysql, I think you must rename debian.conf to 00-debian.conf or 00debian.conf (same the debian package). :)

Thanks

**Comment by graysky2** [comment]
Why would it need to be renamed?  Full path is `/etc/monitorix/conf.d/debian.conf`

**Comment by Tarjaizaid** [comment]
if user add option on file same /etc/monitorix/conf.d/abcd.conf, the debian.conf file can overwrite abcd.conf

With the "00" start name, this should not to happen

**Comment by graysky2** [comment]
I don't see how the package-provided file name matters in this case since diffs would require user intervention.  For Arch Linux, pacman would check the checksum of `/etc/monitorix/conf.d/debian.conf` against what it expects it to be.  If unmodified it overwrites silently, if different it will install the package file to `/etc/monitorix/conf.d/debian.conf.pacnew` and the user is expected to diff the two.  I would think apt-get or aptitude would do something similar, no?

**Comment by Tarjaizaid** [comment]
my previous message was ambiguous

This does not directly concern the configuration files, but the parameters of monitorix

When monitorix is started, configuration file was read one by one

Sat Feb 28 10:05:52 2015 - Loaded main configuration file '/etc/monitorix/monitorix.conf'.
Sat Feb 28 10:05:52 2015 - Loading extra configuration file '/etc/monitorix/conf.d/00-debian.conf'.
Sat Feb 28 10:05:52 2015 - Loading extra configuration file '/etc/monitorix/conf.d/perso.conf'.

if user add option on a file with the name abcd.conf, this file is read before debian.conf.
Monitorix options in debian.conf can overwrite abcd.conf options

**Comment by graysky2** [comment]
OK!  I understand now.  Let's see what Jordi thinks.  

Jordi - If you feel this is needed based on Tarjaizaid's observation, please modify the Makefile accordingly or I can do it for you in a new PR.  You should also consider changing the installation readme file accordingly.

**Comment by mikaku** [comment]
I've checked the `.deb` package and I've seen that it installs the `doc/debian.conf` file as `conf.d/00-debian.conf`. So, I think that it would nice to also follow the same criteria in the `Makefile`.

@graysky2, I've modified myself the `Makefile` and will push the commit in the next minutes. Thanks.

@Tarjaizaid, thanks for your feedback also.

**Pull request merged**
