### PR TITLE
Add Slovak translation of reports/en.html

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by mikaku** [comment]
Shouldn't the file be named as **sk.html** instead of **en.html**?, also, in the HTML there are still some references of the English language, like this:

```
<html lang="en" dir="ltr"> 
```

Please, fix all this and I'll be glad to merge your pull request.

**Comment by jose1711** [comment]
you're right, fixed

**Comment by mikaku** [comment]
I'm still seeing this:

```
 <meta http-equiv="content-language" content="en">
```

Don't fix things so quickly, take your time and do it well.

**Comment by mikaku** [comment]
What is this site?
<http://www.priklad.sk>

**Comment by jose1711** [comment]
priklad in slovak is the same as example in english.

**Comment by mikaku** [comment]
OK, looks fine to me.

**Pull request merged**
